name: html_wrapper
description: A Custom wrapper that convert Widget into html tag.
version: 0.0.2
repository: https://github.com/Antoinegtir/html-wrapper
homepage: https://flutter-seo.web.app
View/report issues: https://github.com/firebase/flutterfire/issues
contributing: https://github.com/Antoinegtir/html-wrapper/CONTRIBUTING.md

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter